### ISSUE TITLE
Apple Health Metric Support

### ISSUE THREAD

**Issue by theospears** [beeminder/BeeSwift#338]
This is a meta-issue tracking support for Apple Health metrics. It includes both metrics that are already supported, along with those which have been requested.

### Activity
- [X] Active energy
- [X] Cycling distance
- [X] Exercise time
- [X] Nike Fuel
- [X] Resting energy
- [ ] Stand hours - Disabled due to #52
- [X] Steps
- [X] Swimming distance
- [X] Swimming strokes
- [X] Walking/running distance
- [ ] Workouts (count) - See #74

### Body Measurements
- [X] Weight

### Heart
- [ ] Max Heart Rate (Requested on Discord)

### Mindfulness
- [X] Mindful minutes - Implemented but buggy, see #284

### Nutrition
- [ ] Caffeine - See #232
- [X] Dietary carbs
- [X] Dietary energy
- [X] Dietary protein
- [X] Dietary saturated fat
- [X] Dietary sodium
- [X] Dietary sugar
- [X] Dietary total fat
- [ ] Vitamin C ([Requested on forum](https://forum.beeminder.com/t/can-we-please-add-more-ios-health-data-points/5263/2))
- [X] Water

### Sleep
- [X] Time in bed
- [X] Time asleep - Can over-report, see #259
- [ ] Wake up time (Requested on Discord)

### Other Data
- [ ] Toothbrushing - See #88

**Comment by dreeves** [comment]
Request from user Matt Niedoba: 

> It would be nice to add workouts of a specific type as a Apple Health integration. Useful if you want to do more of a specific type of activity [eg, yoga] or if you want to make sure you're hitting the requisite number of workouts/week for your training plan (eg marathon training or something).
