### ISSUE TITLE
Ancient Task List Cleanup

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#63]
I'm not sure if this is a good use for a gissue but we have an ancient collection of feedback from 2015 and earlier about the iOS app and I figured maybe I could turn it into a checklist and we could gradually check things off when we either confirm they're no longer relevant or when we've turned them into their own gissues... Holler if this would be better as a wiki or an email or something!

- [ ] melanie saw missing goals. "When I first downloaded it, all goals showed up fine.  Not sure how long that lasted" [4.0]

- [ ] philip: "Having to wait for a clean load of ultra-fresh data would be the wrong trade-off for me, I’d rather see ten-minutes-ago displayed promptly and correctly sorted. ... I think that the ‘reload goals’ button has psychological weight, independent of any technical reason for its continued existence. Might even be something we can count the presses of, as a frustration measure. ... If we can integrate with the 1Password widget, we can get them to include us in their periodic blog post and directory https://blog.agilebits.com/1password-apps/ " [4.0]

- [ ] chuck: "Probably at least half the time I launch it I get an almost totally blank screen, sometimes with an activity spinner (see below screenshot from a few minutes ago) ... I just had a new glitch -- it's the first time I've seen it. I launched the app and only saw 3 (out of a dozen or so) goals, with a gray border below them [screenshot]" [4.0]

- [X] mark: blank screens, "All missing last night on my iPad, two missing currently on my iPhone." [4.0]

- [ ] grant: "first time I opened the app, I was asked to log in. I did so, and everything worked as expected. The new interface looks great! I went back to the app later (I left it in an active state) and that's when the problems started. The goal screen showed nothing by white. I was able to access the options screen, which looked as expected. Returning back to the main screen returned me to an empty white screen. I tried quitting and restarting the app, but the blank screen persists." [4.0]

- [X] robin: "works for me! (on iPad, with iOS 8.3) And I'm loving this new version." [4.0]

- [X] maggie: "I have an iPhone 5s w/ jailbreak and iOS 8.3. No issues with the app." [4.0]

- [X] dustin: "works for me" [4.0]

- [ ] gilles: "seems to work most of the time, but I only have one goal running. Only issue I've seen is that sometimes it will take a really long time to refresh (which admittedly I've also seen on the website before) ... I did notice another issue likely attributable to the fact that I'm running a beta of iOS 9, which is why I didn't report it, but you may want to be aware of it. [dead link] The numbers on the right seem to be misaligned on it." [4.0]

- [X] zach: "noticed some glitches but not regretting upgrade. quitting and relaunching has solved all issues" [4.0]

- [ ] matt: "In general, I’d say it works better than before.  In the previous version, nearly every time I opened the app I had to go into settings and “Reload goals”.  There doesn’t seem to be a need to do this anymore (I see you’ve removed the button). That said, I have had it effectively hang a few times.  It just sat there spinning for several minutes.  I force quit the app and reloaded and everything worked fine.  Otherwise it seems to work fine." [4.0]

- [ ] Aaron can't add the Today widget; Philip can. [3.2]

- [ ] "The widget is working for me, and they are very helpful. Now give me a way to add datapoints!" [3.2]

- [ ] "Today widget appears to be working for me (see screenshot), although it took me a while to figure out how to enable it -- I first looked in the Beeminder app settings, then in iOS Settings-> Beeminder, then iOS Settings-> Notifications, then the Notifications screen, before I finally figured out I had to go to the Today screen itself. Maybe the problems people are having has more to do with iOS's convoluted system of settings & preferences." [3.2]

- [ ] "I haven’t exactly figured out the pattern but when I open the app, most of the time it shows no goals.  I have to click the ‘Settings’ gear and hit reload goals and then they show up.  This behavior was present in every version of the app that I’ve used.  I’m wondering if this is maybe intended behavior in some way because it seems like way too obvious of a bug so I apologize if I’m being dense." [3.2]

- [ ] "A small thing I noticed today.  I’m traveling this week in the Eastern time zone and I have my reminder set for 9pm Central time (where I spend most of my time).  The reminder went off at 10pm Eastern time.  Again, I can totally understand how this might be intended behavior, but I wasn’t sure so I thought I’d report it.  For what it’s worth I have another app set to remind me at 10pm Central time and it went off at 10pm Eastern time as well." [3.2]

- [ ] "I can't see a Today widget" [3.2]

- [ ] "the Today widget didn't show up for me.  iPhone 5, iOS 8.1.3." [3.2]

- [ ] "I don't see Beeminder as an option for Today widgets. That said, I don't see Beeminder in the options for Notifications either. In Beeminder's in-app settings i have enabled notifications but i never get any. On iOS 8.0.2" [3.2]

- [ ] "Notifications has never worked for me in Beeminder on IOS 8 (and still doesn't- beeminder doesn't even appear in the list of apps that have registered for notifications ability in settings). I also don't see any option to add Beeminder to the today screen in the list of apps to include." [3.2]

- [ ] "The today widget works for me! Nice! In the previous version, the app almost never showed all (or sometimes any) of my goals without doing a reload goals. I'll let you guys know if that persists in this version" [3.2]

- [ ] "I just opened the app today and it had no goals. The spinner went for a sec then it showed only one of mine. I had to do the same thing as the last app version: tap the gear, then tap "reload goals". I think this problem existed in the first version of the app, or maybe just an early one. It went away but then came back maybe a month ago? I don't know what version because I just have apps update themselves. [this is adam w of fog creek]" [3.2]

- [ ] "The Today widget is working for me, I added it just now with no trouble at all and it is showing the same data as the app for the three most urgent goals. Thanks for Beeminder, it has really changed my life for the better!" [3.2]

- [ ] "works for me! [screenshot] [later] Hm maybe I lied. I have two beemergencies today that aren't showing up as such." [3.2]

- [ ] "When I checked the beeminder iPhone app it said all of my goals were OK for the day.  I'm guessing that was just out of date information." [very old]

- [ ] "Date can be off by one if you're > GMT + 12" [very old]

- [ ] "'Could not refresh goals' pops up repeatedly sometimes. Regardless of network type or apparent signal quality." [very old]

- [ ] Does the app give any indication of whether or not the datapoint actually got added? "Yes. It says 'Saved' if it's been saved." Is it a persistent indication? or missable if you're not paying attention? (this seems like the most critical thing -- "but i entered my data!") "It goes away. But you then see the datapoint below the graph. And safe days change, if they should." [very old]

- [ ] Sam: "Today when I updated [...] from the iOS app, the time to failure stayed at 0 days. I checked on the web and it was still 0 days. Then I hit the refresh button on the web and it correctly updated to 2 days. Also, in general in the iOS app, it takes a painfully long time to update the time to failure - it would be really nice if this was calculated immediately client side instead of waiting for the graph to update." [very old]

- [ ] John: "I haven't update missed days in a few days. Since I can't do that in the iOS app, I sometimes fall behind. I'll do that in a minute." [very old]

- [ ] John: "The iOS app did not warn that this was about to fail. Maybe your algorithm is off?" [very old]

- [X] Brendan: "Seems when I enter data it adds an extra day to the date, eg I enter 22 1 and it inputs it as 23 1 when I hit submit" [very old]

- [X] Jeremy in Australia: "If I input data for the 19th of December (as in the screenshot attached), the input shown above registers as the 20th (as you can see in the screenshot above the data entry box "20 0.5"). The same problem takes place in all of my goals: I enter one date, and the inputted data is accepted as taking place a day later." [very old]

- [ ] "It seems that 'set a limit' goals don’t trigger any sort of warning in the iPhone app, and then the 'pessimistic presumption' kicks in and pushes you over the line…" [very old]

- [ ] "Sometimes connections are bad. Or the person isn't waiting until seeing 'saved'. Hitting back seems to cause the datapoint to not complete." [very old]

- [ ] Miranda: "I am finding that when I use my iphone app, Beeminder does not always save the information that I enter.  When I periodically go to the actual site using a browser, I see that data I entered on my phone has disappeared." [very old]

- [ ] "Whenever I open the iPhone app, I get like four 'Could not refresh goals' alerts. Even though I have a data connection and am connected to the wifi. Happens every time. Exiting the app and going back in to it immediately does not produce the error. You have to leave it for a period of time, it seems." [very old]

- [ ] "I learned not to trust the iPhone's view of things. When I wanted to know the status, I'd either do a full refresh from the settings pane, or go to the website." [very old]

- [ ] "datapoint history dates are often... confused. The most recent datapoint often had an off-by-one error, in either direction." philip has screenshots, at GMT+0. (Still occurs in version 3 beta)

- [ ] "I've got dozens of goals, so usually just about the time that I find the goal that I want to update, the refresh-on-launch kicks in and blanks the screen." [very old]

- [ ] "iPhone app keeps its own countdown, so will often declare a goal derailed, at least until the refresh properly refreshes." [very old]

- [X] "It's strange that the number in the graph and the number beside the graph don't match. i.e. one is safe days, the other is the countdown. But it's not clear, and there's no room for text." [very old]

**Comment by krugerk** [comment]
Let us see how far we can get with these chunks of feedback in the form of one gissue.

Some themes that stick out for me are data syncing (how up-to-date is the data displayed in the app), using the app with slow/absent connection, timezone (perhaps goal deadline) issues, notifications, and hello today widget.

What is the convention for the list? 
 -> task item; description; app version
What does checked/unchecked mean here? Resolved? Not relevant? Confirmed? Task done (in whatever form that might be)?


Someone else might have data on the installation base - which percentage of active users is on which iOS version.

Any of the ones mentioning anything pre iOS 9 and even pre iOS 10 could be marked done/no longer relevant.
The ones about how to use notifications or use the today widget could also be marked the same (done/no longer relevant).



Those that passed through these filters:
- [ ] philip: "Having to wait for a clean load of ultra-fresh data would be the wrong trade-off for me, I’d rather see ten-minutes-ago displayed promptly and correctly sorted. ... I think that the ‘reload goals’ button has psychological weight, independent of any technical reason for its continued existence.
- [ ] matt: "In general, I’d say it works better than before. In the previous version, nearly every time I opened the app I had to go into settings and “Reload goals”. There doesn’t seem to be a need to do this anymore (I see you’ve removed the button). That said, I have had it effectively hang a few times. It just sat there spinning for several minutes. I force quit the app and reloaded and everything worked fine. Otherwise it seems to work fine." [4.0]
--> Interesting. How beneficial might it be to switch to a push (beeminder server sends updates to apps; apps do not poll for new data) model?

**Comment by dreeves** [comment]
> What is the convention for the list?

I just pasted chunks of feedback, mostly quotes from users, and then put the app version in brackets.

> What does checked/unchecked mean here? Resolved? Not relevant? Confirmed? Task done (in whatever form that might be)?

Either not relevant anymore (already resolved, generally, or `cnr`) or moved to its own gissue.

> which percentage of active users is on which iOS version

Andy may know that but I think mostly we don't care. If you have a problem and you're not on the latest version then get the heck onto the latest version.

> Any of the ones mentioning anything pre iOS 9 and even pre iOS 10 could be marked done/no longer relevant.
> The ones about how to use notifications or use the today widget could also be marked the same (done/no longer relevant).

Agreed!

**Comment by andrewpbrett** [comment]
I read through these and I don't think anything is going to be worth investigating. Since 4.0 the app has completely changed the way it fetches and stores data, so unless I missed something that's post-4.0, I think this should be closed.
